version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-nestjs-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:     
      - DATABASE_HOST = ${DATABASE_HOST}
      - DATABASE_PORT = ${DATABASE_PORT}
      - DATABASE_USER = ${DATABASE_USER}
      - DATABASE_PASSWORD = ${DATABASE_PASSWORD}
      - DATABASE_NAME = ${DATABASE_NAME}
    networks:
      - app-network

  db:
    image: postgres:latest
    ports:
      - "5433:5432"  
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge



    